### ISSUE TITLE
剪刀会直接将绊线钩之间的线剪断

### ISSUE THREAD

**Issue by Linf9** [LuminolMC/LightingLuminol#2]
### 服务端版本 LightingLuminolMC Version

fec9e6c

### 预期的行为 Expected behavior

如原版一样

### 观测到的实际行为 Observed/Actual behavior

剪刀会直接将绊线钩之间的线剪断

### 复现步骤 Steps/models to reproduce

正常放置两个绊线钩，之间用线连接，用剪刀左键之间的线，线会直接被破坏

### 插件与数据包列表。 Plugin and Datapack List.

![屏幕截图 2024-04-20 133102](https://github.com/LuminolMC/LightingLuminol/assets/167072730/4779a014-ccc7-4ff2-a58a-5561baae3017)
![屏幕截图 2024-04-20 132907](https://github.com/LuminolMC/LightingLuminol/assets/167072730/482e5561-5566-4801-9a1f-ef0d57d4e134)

**Comment by 90257550** [comment]
我服使用luminol后玩家反馈刷线机有问题

**Comment by Klop233** [comment]
使用 `Folia` 时是否有同样问题

**Comment by Linf9** [comment]
kaiiju中没用问题

**Comment by MrHua269** [comment]
emmm，刷线要在paper的配置文件打开，因为folia更新了paper之后paper对大量原版特性的修复做了修改并在他们的配置文件中添加了配置项，所以luminol包括lightingluminol不会再添加重复的配置项了

**Comment by 90257550** [comment]
我到家试试

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
