### ISSUE TITLE
Update to 1.21 pls

### ISSUE THREAD

**Issue by GaLaXyILY** [LuminolMC/LightingLuminol#6]
### 描述你希望添加的功能。 Describe the feature you'd like.

Update to 1.21 pls

### 其他 Other

Update to 1.21 pls

**Comment by NatJerry** [comment]
the upstream Folia havent updated to 1.21 yet

**Comment by Piecuuu** [comment]
This should be reopened, since Luminol is now on 1.21 on dev. Now we're waiting for LightingLuminol.
